sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t demoinfogo .
  - mkdir artifacts
  - docker run -v ${PWD}/artifacts:/demoinfogo/build -ti demoinfogo ./docker.sh

script:
  - ls artifacts/demoinfogo
  - cd artifacts && zip -r demoinfogo-linux.zip demoinfogo libs/
